// Arriba del archivo
export const INSPECCION_A_ITEMS_UCL = {
  lubricantes: [
    {
      ok: "lbprOk",
      pm: "lbprPM",
      agua: "lbprAgua",
      sucio: "lbprSucio",
      esp: "lbprEsp",
      label: "Lubricante Reductor",
    },
    {
      ok: "lsfOk",
      pm: "lsfPM",
      agua: "lsfAgua",
      sucio: "lsfSucio",
      esp: "lsfEsp",
      label: "Rodamientos Rodillo",
    },
    {
      ok: "lsfOk",
      pm: "lsfPM",
      agua: "lsfAgua",
      sucio: "lsfSucio",
      esp: "lsfEsp",
      label: "Dispositivo Inversor",
    },
    {
      ok: "lsfOk",
      pm: "lsfPM",
      agua: "lsfAgua",
      sucio: "lsfSucio",
      esp: "lsfEsp",
      label: "Corona Superior",
    },
    {
      ok: "lsfOk",
      pm: "lsfPM",
      agua: "lsfAgua",
      sucio: "lsfSucio",
      esp: "lsfEsp",
      label: "Cadena y Transmición",
    },
    
  ],
  inversor: [
    {
      // ok: "emOk",
      // reten: "emAlRet",
      // rodamiento: "emAlRod",
      // diametro: "emDiam",
      // deformado: "emDef",
      // esp: "emEsp",
      label: "Pernos extremo cadena",
    },
    {
      // ok: "emOk",
      // reten: "emAlRet",
      // rodamiento: "emAlRod",
      // diametro: "emDiam",
      // deformado: "emDef",
      // esp: "emEsp",
      label: "Eje pívot",
    },{
      // ok: "emOk",
      // reten: "emAlRet",
      // rodamiento: "emAlRod",
      // diametro: "emDiam",
      // deformado: "emDef",
      // esp: "emEsp",
      label: "Ejes concéntricos",
    },{
      // ok: "emOk",
      // reten: "emAlRet",
      // rodamiento: "emAlRod",
      // diametro: "emDiam",
      // deformado: "emDef",
      // esp: "emEsp",
      label: "Ejes excéntricos",
    },
    {
      // ok: "emOk",
      // reten: "emAlRet",
      // rodamiento: "emAlRod",
      // diametro: "emDiam",
      // deformado: "emDef",
      // esp: "emEsp",
      label: "Ruedas metálicas",
    },
    {
      // ok: "emOk",
      // reten: "emAlRet",
      // rodamiento: "emAlRod",
      // diametro: "emDiam",
      // deformado: "emDef",
      // esp: "emEsp",
      label: "Estructura(Nudo)",
    },
  ],
};

export const INSPECCION_B_ITEMS_UCL = {
  rodamientos: [
    {
      ok: "axOk",
      picado: "axPic",
      laminado: "axLam",
      fallaEnJaula: "axFj",
      desgaste: "axDesg",
      esp: "axEsp",
      label: "Axial 294158",
    },
    {
      ok: "gsOk",
      picado: "gsPic",
      laminado: "guiaSup6022.laminado",
      fallaEnJaula: "gsFj",
      desgaste: "gsDesg",
      esp: "gsEsp",
      label: "Guía Superior 6022",
    },
    {
      ok: "giOk",
      picado: "giPic",
      laminado: "giLam",
      fallaEnJaula: "giFj",
      desgaste: "giDesg",
      esp: "giEsp",
      label: "Guía Inferior 6017",
    },
    {
      ok: "frOk",
      picado: "frPic",
      laminado: "frLam",
      fallaEnJaula: "frFj",
      desgaste: "frDesg",
      esp: "frEsp",
      label: "Freno 6005-1RS-Z",
    },
    {
      ok: "arOk",
      picado: "arPic",
      laminado: "arLamo",
      fallaEnJaula: "arFj",
      desgaste: "arDesg",
      esp: "arEsp",
      label: "Antirretorno CSK25-PP-C3",
    },
  ],

  transmision: [
    {
      ok: "corOk",
      picado: "corPic",
      desgastado: "corDesg",
      roto: "corRot",
      esp: "corEsp",
      label: "Corona",
    },
    {
      ok: "pinOk",
      picado: "pinPic",
      desgastado: "piDesg",
      roto: "pinRot",
      esp: "pinEsp",
      label: "Piñón",
    },
    {
      ok: "pfOk",
      picado: "pfPic",
      desgastado: "pfDesg",
      roto: "pfRot",
      esp: "pfEsp",
      label: "Pastillas de Freno",
    },
  ],
};

export const INSPECCION_C_ITEMS_UCL = {
  sistemaHidraulicoPcpVh60: [
    {
      ok: "bomOk",
      fuga: "bomFug",
      roto: "bomRot",
      eficiencia: "bomEf",
      esp: "bomEsp",
      label: "Bomba",
    },
    {
      ok: "manOk",
      fuga: "manFug",
      roto: "manRot",
      eficiencia: "manEf",
      esp: "manEsp",
      label: "Manifold",
    },
    {
      ok: "calOk",
      fuga: "calFug",
      roto: "calRot",
      eficiencia: "calEf",
      esp: "calEsp",
      label: "Cáliper",
    },
    {
      ok: "cmOk",
      fuga: "cmFug",
      roto: "cmRot",
      eficiencia: "cmEf",
      esp: "cmEsp",
      label: "Conjunto Mangueras",
    },
  ],
  poleaPcpVh60: [
    {
      ok: "bomOk",
      fisura: "alojRod",
      poros: "alojRet",
      diametroInad: "diam",
      numTraz: "def",
      esp: "esp",
      label: "Bomba",
    },
  ],
}

